version: "3"
services:
  vote:
    image: voting-app
    ports:
      - 8000:80
  result:
    image: result-app
    ports:
      - 5001:80
  worker:
    image: worker-app
  redis:
    image: redis:5.0-alpine3.10
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
volumes:
  db-data:
    driver: local
